namespace AgenticLeague.Models;

/// <summary>
/// Agent identity and initialization state.
/// Persisted as profile.json in the agent's workspace.
/// </summary>
public class AgentProfile
{
    /// <summary>
    /// Unique agent identifier (e.g., "agent-01").
    /// </summary>
    public string AgentId { get; set; } = string.Empty;

    /// <summary>
    /// Team name (e.g., "The Python Pandas").
    /// Generated by the agent on first launch.
    /// </summary>
    public string TeamName { get; set; } = string.Empty;

    /// <summary>
    /// Path to the team logo image (relative to agent workspace).
    /// </summary>
    public string? LogoPath { get; set; }

    /// <summary>
    /// OpenRouter model being used for this agent.
    /// </summary>
    public string ModelName { get; set; } = string.Empty;

    /// <summary>
    /// When the agent profile was first created.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// True after the agent has generated strategy, team name, and logo.
    /// </summary>
    public bool IsInitialized { get; set; }
}
