namespace AgenticLeague.Models;

/// <summary>
/// Agent identity and initialization state.
/// Persisted by LeagueAPI and consumed by AgenticLeague through API/MCP operations.
/// </summary>
public class AgentProfile
{
    /// <summary>
    /// Unique agent identifier (e.g., "agent-01").
    /// </summary>
    public string AgentId { get; set; } = string.Empty;

    /// <summary>
    /// Team name (e.g., "The Python Pandas").
    /// Generated by the agent on first launch.
    /// </summary>
    public string TeamName { get; set; } = string.Empty;

    /// <summary>
    /// Model being used for this agent.
    /// </summary>
    public string ModelName { get; set; } = string.Empty;

    /// <summary>
    /// Model connection/provider being used for this agent ("OpenRouter").
    /// </summary>
    public string Connection { get; set; } = string.Empty;

    /// <summary>
    /// When the agent profile was first created.
    /// </summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>
    /// When the agent last updated its profile (e.g., after a strategy change).
    /// </summary>
    public DateTimeOffset LastUpdatedAt { get; set; }

    /// <summary>
    /// True after the agent has generated strategy, team name, and logo.
    /// </summary>
    public bool IsBootstrapped { get; set; }

    /// <summary>
    /// True when this profile participates in league startup.
    /// </summary>
    public bool IsEnabled { get; set; } = true;
}
