// <auto-generated />
using System;
using LeagueAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeagueAPI.Migrations
{
    [DbContext(typeof(LeagueApiDbContext))]
    [Migration("20260731203721_AddPlayerSportradarId")]
    partial class AddPlayerSportradarId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeagueAPI.Models.AgentProfile", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Connection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBootstrapped")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("AgentId");

                    b.HasIndex("IsEnabled");

                    b.ToTable("agent_profiles", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.DecisionEntity", b =>
                {
                    b.Property<int>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DecisionId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CachedInputTokenCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("integer");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("integer");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReasoningTokenCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("DecisionId");

                    b.HasIndex("AgentId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("decisions", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.FantasyProsRankingPlayerEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("CbsPlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlayerByeWeek")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("PlayerEcrDelta")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PlayerEligibility")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlayerFilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PlayerOwnedAverage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("PlayerOwnedEspn")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("PlayerOwnedYahoo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PlayerPageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PlayerPositionId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlayerPositions")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlayerShortName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlayerTeamId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlayerYahooId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlayerYahooPositions")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PositionRank")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RankAverage")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RankEcr")
                        .HasColumnType("integer");

                    b.Property<string>("RankMaximum")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RankMinimum")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RankStandardDeviation")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("SportsDataId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("PlayerYahooId");

                    b.HasIndex("SportsDataId");

                    b.HasIndex("Season", "Week");

                    b.ToTable("fantasypros_ranking_players", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.FantasyProsScoreSyncRun", b =>
                {
                    b.Property<Guid>("SyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlreadyProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobETag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("EndWeek")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("MatchedPlayerCount")
                        .HasColumnType("integer");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("ServedScoring")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ServedSeason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("UnmatchedDstCount")
                        .HasColumnType("integer");

                    b.Property<int?>("UnmatchedPlayerCount")
                        .HasColumnType("integer");

                    b.HasKey("SyncRunId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("Season");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("ContainerName", "BlobName", "Season", "EndWeek", "ContentHash");

                    b.ToTable("fantasypros_score_sync_runs", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.FantasyProsSyncRun", b =>
                {
                    b.Property<Guid>("SyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlreadyProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobETag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("SyncRunId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("ContainerName", "BlobName", "Season", "Week", "RetrievedAtUtc");

                    b.ToTable("fantasypros_sync_runs", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.LeagueStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("league_state", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Phase = "free_agency",
                            Season = 2025,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "manual",
                            Week = 0
                        });
                });

            modelBuilder.Entity("LeagueAPI.Models.MatchupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwayAgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("AwayPoints")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("HomeAgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("HomePoints")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTie")
                        .HasColumnType("boolean");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<string>("WinnerAgentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Week", "HomeAgentId");

                    b.ToTable("matchups", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.PlayerEntity", b =>
                {
                    b.Property<string>("SleeperPlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("AuctionValue")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageDraftPosition")
                        .HasColumnType("numeric");

                    b.Property<int?>("ByeWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("FantasyDataId")
                        .HasColumnType("integer");

                    b.Property<string>("FantasyPositionsTokenized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("LastSeasonFantasyPoints")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PlayerOwnedAverage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PositionRank")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ProjectedFantasyPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("RankAverage")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchFullNameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sport")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SportradarId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TeamAbbr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YahooId")
                        .HasColumnType("integer");

                    b.HasKey("SleeperPlayerId");

                    b.HasIndex("ByeWeek");

                    b.HasIndex("FantasyDataId");

                    b.HasIndex("SearchFullNameNormalized");

                    b.HasIndex("SportradarId");

                    b.HasIndex("YahooId");

                    b.HasIndex("TeamAbbr", "Position");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.RosterAssignmentEntity", b =>
                {
                    b.Property<Guid>("RosterAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcquisitionSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SleeperPlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("BN");

                    b.HasKey("RosterAssignmentId");

                    b.HasIndex("AgentId");

                    b.HasIndex("SleeperPlayerId")
                        .IsUnique();

                    b.HasIndex("AgentId", "SlotType")
                        .IsUnique()
                        .HasFilter("\"SlotType\" <> 'BN'");

                    b.ToTable("roster_assignments", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.ScoringTemplate", b =>
                {
                    b.Property<string>("TemplateKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TemplateKey");

                    b.HasIndex("IsActive");

                    b.ToTable("scoring_templates", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.ScoringTemplateRule", b =>
                {
                    b.Property<string>("TemplateKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StatId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Modifier")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("StatName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TemplateKey", "StatId");

                    b.ToTable("scoring_template_rules", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.SleeperSyncRun", b =>
                {
                    b.Property<Guid>("SyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlreadyProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobETag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BlobName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("SyncRunId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("ContainerName", "BlobName", "RetrievedAtUtc");

                    b.ToTable("sleeper_sync_runs", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.SportsDataFantasyPlayerEntity", b =>
                {
                    b.Property<int>("SportsDataPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuctionValue")
                        .HasColumnType("integer");

                    b.Property<int?>("AuctionValuePPR")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageDraftPosition")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPosition2QB")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPositionDynasty")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPositionIDP")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPositionPPR")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPositionRookie")
                        .HasColumnType("numeric");

                    b.Property<int?>("ByeWeek")
                        .HasColumnType("integer");

                    b.Property<string>("FantasyPlayerKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("LastSeasonFantasyPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ProjectedFantasyPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SportsDataPlayerId");

                    b.ToTable("sportsdata_fantasy_players", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.SportsDataSyncRun", b =>
                {
                    b.Property<Guid>("SyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlreadyProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobETag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BlobName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("SyncRunId");

                    b.HasIndex("ContentHash");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("ContainerName", "BlobName", "RetrievedAtUtc");

                    b.ToTable("sportsdata_sync_runs", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.WaiverClaimEntity", b =>
                {
                    b.Property<Guid>("WaiverClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddSleeperPlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ClaimOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DropSleeperPlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<int>("PriorityAtSubmission")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("WaiverClaimId");

                    b.HasIndex("Season", "Week", "Status");

                    b.HasIndex("Season", "Week", "AgentId", "ClaimOrder");

                    b.ToTable("waiver_claims", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.WaiverPriorityEntity", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AgentId");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.ToTable("waiver_priority", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.WaiverProcessRunEntity", b =>
                {
                    b.Property<Guid>("WaiverProcessRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClaimsFailed")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimsProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimsSucceeded")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("WaiverProcessRunId");

                    b.HasIndex("Season", "Week");

                    b.ToTable("waiver_process_runs", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyPlayerPoint", b =>
                {
                    b.Property<long>("WeeklyPlayerPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WeeklyPlayerPointId"));

                    b.Property<string>("BreakdownJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FantasyPoints")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("WeeklyPlayerStatId")
                        .HasColumnType("bigint");

                    b.HasKey("WeeklyPlayerPointId");

                    b.HasIndex("TemplateKey");

                    b.HasIndex("WeeklyPlayerStatId", "TemplateKey")
                        .IsUnique();

                    b.ToTable("weekly_player_points", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyPlayerScoreEntity", b =>
                {
                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("FantasyProsPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Points")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("PositionId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SleeperPlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SyncRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Season", "Week", "FantasyProsPlayerId");

                    b.HasIndex("SleeperPlayerId");

                    b.HasIndex("SyncRunId");

                    b.HasIndex("Season", "Week");

                    b.ToTable("weekly_player_scores", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyPlayerStat", b =>
                {
                    b.Property<long>("WeeklyPlayerStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WeeklyPlayerStatId"));

                    b.Property<string>("EditorialTeamAbbr")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("SleeperPlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SyncRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("YahooPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("WeeklyPlayerStatId");

                    b.HasIndex("SleeperPlayerId");

                    b.HasIndex("SyncRunId");

                    b.HasIndex("Season", "Week", "Position");

                    b.HasIndex("Season", "Week", "YahooPlayerId")
                        .IsUnique();

                    b.ToTable("weekly_player_stats", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyPlayerStatValue", b =>
                {
                    b.Property<long>("WeeklyPlayerStatId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatId")
                        .HasColumnType("integer");

                    b.Property<string>("StatName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("WeeklyPlayerStatId", "StatId");

                    b.HasIndex("StatId");

                    b.ToTable("weekly_player_stat_values", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyRosterSnapshot", b =>
                {
                    b.Property<long>("WeeklyRosterSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WeeklyRosterSnapshotId"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("SleeperPlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("WeeklyRosterSnapshotId");

                    b.HasIndex("Season", "Week", "AgentId");

                    b.HasIndex("Season", "Week", "AgentId", "SleeperPlayerId")
                        .IsUnique();

                    b.ToTable("weekly_roster_snapshots", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.YahooOAuthStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorizationState")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("ExpiresInSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastRefreshedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TokenType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("yahoo_oauth_state", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.YahooPlayerIdOverrideEntity", b =>
                {
                    b.Property<int>("YahooPlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SleeperPlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("YahooPlayerId");

                    b.HasIndex("SleeperPlayerId");

                    b.ToTable("yahoo_player_id_overrides", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.YahooSyncRun", b =>
                {
                    b.Property<Guid>("SyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("MatchedPlayerCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("UnmatchedPlayerCount")
                        .HasColumnType("integer");

                    b.Property<int?>("Week")
                        .HasColumnType("integer");

                    b.HasKey("SyncRunId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("GameKey", "Season", "Week");

                    b.ToTable("yahoo_sync_runs", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.RosterAssignmentEntity", b =>
                {
                    b.HasOne("LeagueAPI.Models.PlayerEntity", null)
                        .WithMany()
                        .HasForeignKey("SleeperPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LeagueAPI.Models.ScoringTemplateRule", b =>
                {
                    b.HasOne("LeagueAPI.Models.ScoringTemplate", "ScoringTemplate")
                        .WithMany("Rules")
                        .HasForeignKey("TemplateKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringTemplate");
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyPlayerPoint", b =>
                {
                    b.HasOne("LeagueAPI.Models.ScoringTemplate", "ScoringTemplate")
                        .WithMany("WeeklyPlayerPoints")
                        .HasForeignKey("TemplateKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueAPI.Models.WeeklyPlayerStat", "WeeklyPlayerStat")
                        .WithMany("Points")
                        .HasForeignKey("WeeklyPlayerStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringTemplate");

                    b.Navigation("WeeklyPlayerStat");
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyPlayerStat", b =>
                {
                    b.HasOne("LeagueAPI.Models.YahooSyncRun", "SyncRun")
                        .WithMany("WeeklyPlayerStats")
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SyncRun");
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyPlayerStatValue", b =>
                {
                    b.HasOne("LeagueAPI.Models.WeeklyPlayerStat", "WeeklyPlayerStat")
                        .WithMany("StatValues")
                        .HasForeignKey("WeeklyPlayerStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyPlayerStat");
                });

            modelBuilder.Entity("LeagueAPI.Models.ScoringTemplate", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("WeeklyPlayerPoints");
                });

            modelBuilder.Entity("LeagueAPI.Models.WeeklyPlayerStat", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("StatValues");
                });

            modelBuilder.Entity("LeagueAPI.Models.YahooSyncRun", b =>
                {
                    b.Navigation("WeeklyPlayerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
