// <auto-generated />
using System;
using LeagueAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeagueAPI.Migrations
{
    [DbContext(typeof(LeagueApiDbContext))]
    partial class LeagueApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeagueAPI.Models.PlayerEntity", b =>
                {
                    b.Property<string>("SleeperPlayerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("AuctionValue")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageDraftPosition")
                        .HasColumnType("numeric");

                    b.Property<int?>("ByeWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("FantasyDataId")
                        .HasColumnType("integer");

                    b.Property<string>("FantasyPositionsTokenized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("LastSeasonFantasyPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ProjectedFantasyPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchFullNameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sport")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TeamAbbr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YahooId")
                        .HasColumnType("integer");

                    b.HasKey("SleeperPlayerId");

                    b.HasIndex("ByeWeek");

                    b.HasIndex("FantasyDataId");

                    b.HasIndex("SearchFullNameNormalized");

                    b.HasIndex("YahooId");

                    b.HasIndex("TeamAbbr", "Position");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.SleeperSyncRun", b =>
                {
                    b.Property<Guid>("SyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("PayloadSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("SnapshotRelativePath")
                        .HasMaxLength(520)
                        .HasColumnType("character varying(520)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("SyncRunId");

                    b.ToTable("sleeper_sync_runs", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.SportsDataFantasyPlayerEntity", b =>
                {
                    b.Property<int>("SportsDataPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("AuctionValue")
                        .HasColumnType("integer");

                    b.Property<int?>("AuctionValuePPR")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageDraftPosition")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPosition2QB")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPositionDynasty")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPositionIDP")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPositionPPR")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AverageDraftPositionRookie")
                        .HasColumnType("numeric");

                    b.Property<int?>("ByeWeek")
                        .HasColumnType("integer");

                    b.Property<string>("FantasyPlayerKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("LastSeasonFantasyPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ProjectedFantasyPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SportsDataPlayerId");

                    b.ToTable("sportsdata_fantasy_players", (string)null);
                });

            modelBuilder.Entity("LeagueAPI.Models.SportsDataSyncRun", b =>
                {
                    b.Property<Guid>("SyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("SyncRunId");

                    b.ToTable("sportsdata_sync_runs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
