namespace LeagueAPI.Models;

/// <summary>
/// Agent identity, model configuration, and initialization state.
/// </summary>
public sealed class AgentProfile
{
    /// <summary>
    /// Unique agent identifier (e.g., "player-01").
    /// </summary>
    public string AgentId { get; set; } = string.Empty;

    /// <summary>
    /// Team name generated by the agent during bootstrap.
    /// </summary>
    public string TeamName { get; set; } = string.Empty;

    /// <summary>
    /// Model being used for this agent.
    /// </summary>
    public string ModelName { get; set; } = string.Empty;

    /// <summary>
    /// Model connection/provider being used for this agent (e.g., "OpenRouter" or "MSFoundry").
    /// </summary>
    public string Connection { get; set; } = string.Empty;

    /// <summary>
    /// When the agent profile was first created.
    /// </summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>
    /// When the agent last updated its profile.
    /// </summary>
    public DateTimeOffset LastUpdatedAt { get; set; }

    /// <summary>
    /// True after the agent has generated strategy, team name, and logo content.
    /// </summary>
    public bool IsBootstrapped { get; set; }

    /// <summary>
    /// True when this profile participates in league startup.
    /// </summary>
    public bool IsEnabled { get; set; } = true;
}
